### ISSUE TITLE
Need more demos, such as multi-model structures?

### ISSUE THREAD

**Issue by melbjerry** [WAMAWAMA/wama_modules#2]
Wow, thank you for the demo you provided. They look very concise.
BTW, do you have any plans to implement some multi-modal models? For example, the 'co-attention model' mentioned in this paper
[An Empirical Study of Training End-to-End Vision-and-Language Transformers](https://openaccess.thecvf.com/content/CVPR2022/html/Dou_An_Empirical_Study_of_Training_End-to-End_Vision-and-Language_Transformers_CVPR_2022_paper.html)

**Comment by WAMAWAMA** [comment]
I will add more demos in the future (like the one you suggest), so stay tuned😆
