### ISSUE TITLE
word embedding weights?

### ISSUE THREAD

**Issue by SihanLu212** [WAMAWAMA/wama_modules#3]
https://github.com/WAMAWAMA/wama_modules/blob/main/demo/multi_label/Demo_CVPR2019_MultiLabel_ML_GCN.py#L129

hi, tks for your multi-labl codes, and could you share this weights `cache=r'C:\git\.vector_cache'` below?

```python

# get word embedding
glove = vocab.GloVe(name="6B", dim=300, cache=r'C:\git\.vector_cache')

```

**Comment by WAMAWAMA** [comment]
In fact, you can just not use this parameter, the weight will be downloaded automatically 👍
