### ISSUE TITLE
whats the meaning of Support multi-class per label?

### ISSUE THREAD

**Issue by 7ml** [WAMAWAMA/wama_modules#4]
Thanks for your code in simple style b(￣▽￣)d, but I cannot under stand the "Support multi-class per label" in the table of multi-label network structures, whats the meaning of it ?

**Comment by WAMAWAMA** [comment]
a label can be binary or multi-label, such as binary-class label "gender", with male or female,  or multi-class label "color" with red/blue/yellow and so on
