### ISSUE TITLE
pretrained weights of Radimagenet

### ISSUE THREAD

**Issue by agoclover** [WAMAWAMA/wama_modules#6]
the original radimagenet provides 4 networks's weights, but i only find one (resnet) in your repo?
https://github.com/BMEII-AI/RadImageNet

**Comment by WAMAWAMA** [comment]
Because the weights are saved in different orders in Torch and Keras, so currently only ResNet's pre-training weights have been successfully converted from Keras to Torch format. For more details please refer to the official issue https://github.com/BMEII-AI/RadImageNet/issues/3
